#!/bin/sh
#
# Jason White <jdwhite@menelos.com>
#
# Set 'NETWORKING_flags' in rc.conf to include the list of interfaces 
# that should have an IPv4 address before continuing with rc.pkgsrc 
# startup. 

# PROVIDE: NETWORKING NETWORK

# This is a dummy dependency for services which require networking
# to be operational before starting.

$_rc_subr_loaded . /etc/rc.subr

name="NETWORKING"
start_cmd="NETWORKING_start"
stop_cmd=":"

NETWORKING_start() {
	# For Darwin.
	/usr/sbin/ipconfig setverbose 1

	# Wait up to 60 seconds for each specified interface to have an
	# address assigned.
	for IF in $rc_flags ; do
		addr=""
		slept=0
		until [ "x${addr}" != "x" ]; do
			addr=$(/usr/sbin/ipconfig getifaddr $IF)
			if [ "x$addr" = "x" ]; then
				echo NETWORKING ${IF}: awaiting address assignment
				sleep 5
				slept=$((slept+5))
			else
				echo NETWORKING ${IF}: address is $addr
			fi
			if [ $slept -gt 59 ]; then
				echo NETWORKING ${IF}: timeout awaiting address assignment
				break;
			fi
		done
	done
}

load_rc_config $name
run_rc_command "$1"
